version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
      - "3306"
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    healthcheck:
      test: 'curl -kfsSL https://localhost/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    expose: 
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hboissel/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hboissel/data/mariadb'

networks:
    inception:
      name: inception
      driver: bridge
